
# docker-compose logs -f face-api
# LOGS inside

services:
  # Сервис с FastAPI-приложением
  face-api:
    build: .                            # Собираем Docker-образ из Dockerfile в текущей директории
    env_file:
      - .env                            # Загружаем переменные окружения из .env (например, LOG_LEVEL)
    ports:
      - "8000:8000"                     # Пробрасываем порт 8000 контейнера на хост
    depends_on:
      - qdrant                         # Сначала запускаем Qdrant, затем этот сервис
    volumes:
      - .:/app                         # Монтируем текущую папку проекта в контейнер как /app
                                       # Это позволяет изменять код локально без пересборки образа
      - ./id_counter.txt:/app/id_counter.txt  #  Связь между локальным и контейнером

  # Сервис Qdrant (векторная база данных)
  qdrant:
    image: qdrant/qdrant               # Используем официальный образ Qdrant из Docker Hub
    ports:
      - "6333:6333"                    # REST API
      - "6334:6334"                    # gRPC API (не обязателен, но пусть будет)
    volumes:
      - qdrant_storage:/qdrant/storage # Монтируем том, чтобы данные Qdrant сохранялись между перезапусками

# 🗃Объявляем volume — область для хранения данных Qdrant
volumes:
  qdrant_storage:


